# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Place.create(name: "Split, Croatia", description: "A nice studio apartment in the heart of Split. It's beautifully decorated and it is a nice place to come and rest after a long day working or touristing. The location is perfect and there are supermarkets and restaurants a couple of steps away. It is also located on the road to a beautiful park that have some of the nicest views of Split. The only bad thing is that since it is located on the ground floor of a highly transited street, the noises can be very loud making it hard to sleep or waking you up early in the mornings.", created_at: "2016-01-04 11:23:32", updated_at: "2016-01-14 16:54:28", image_url: "portablu1.png", internet_speed: "Over 30mbps", short_term_rental: "Yes", level_of_noise: "Bad", walkability: "Great", food: "Accessible", ac_heater: "Only AC")

Place.create(name: "Lisbon, Portugal", description: "Cozy apartment in a unique neighborhood in a central place. If you want a portuguese experience, this apartment is perfect. The neighbors are all nice and will provide an insight of life in Lisbon. Rooms are comfortable, there's a kitchen, family room and dining room and the whole apartment is beautifully decorated. You can walk to the main sites from the apartment as well as to stores, supermarkets and restaurants.", created_at: "2016-01-05 17:24:00", updated_at: "2016-01-14 16:58:05", image_url: "lisboa1.png", internet_speed: "Over 30mbps", short_term_rental: "Yes", level_of_noise: "Okay", walkability: "Great", food: "Accessible", ac_heater: "Heater")

Place.create(name: "Seville, Spain", description: "Awesome apartment in a great location close to the main park in the city. The studio apartment has two bathrooms (one with a bathtub), a kitchen, a family room, dining room and two bedrooms. If you are a walker, you'll have no trouble reaching the center of the city through the park which is just next door, or following the river, but it can take half an hour to get to the center. Internet worked perfectly. There is a little bit of street noise, and since it is a converted space with no number on the door, it is hard to locate.", created_at: "2016-01-05 17:33:56", updated_at: "2016-01-14 17:00:56", image_url: "sevilla1.png", internet_speed: "Over 30mbps", short_term_rental: "Yes", level_of_noise: "Okay", walkability: "Good", food: "Accessible", ac_heater: "AC and Heater")

Place.create(name: "Gibraltar", description: "Charming apartment in Old Town, perfectly located. Gibraltar is very small so you can walk everywhere, but this apartment is very close to the Main Street. You have to go up several flights of stairs to reach it. The apartment is nicely decorated with a kitchen, bathroom, family and dining rooms. It can get very noisy with several constructions always going on around the neighborhood.", created_at: "2016-01-05 17:34:22", updated_at: "2016-01-14 17:05:00", image_url: "gibraltar1.png", internet_speed: "Over 30mps", short_term_rental: "Yes", level_of_noise: "Bad", walkability: "Great", food: "Accessible", ac_heater: "Heater")