# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
Place.create(name: "Split, Croatia", description: "A nice studio apartment in the heart of Split. It's beautifully decorated and it is a nice place to come and rest after a long day working or touristing. The location is perfect and there are supermarkets and restaurants a couple of steps away. It is also located on the road to a beautiful park that have some of the nicest views of Split. The only bad thing is that since it is located on the ground floor of a highly transited street, the noises can be very loud making it hard to sleep or waking you up early in the mornings.", created_at: "2016-01-04 11:23:32", updated_at: "2016-01-14 16:54:28", internet_speed: "Over 30mbps", short_term_rental: "Yes", level_of_noise: "Bad", walkability: "Great", link: "https://www.airbnb.com/rooms/7223196", city: "Split", type: "Apartment", country_id: 57 )

Place.create(name: "Lisbon, Portugal", description: "Cozy apartment in a unique neighborhood in a central place. If you want a portuguese experience, this apartment is perfect. The neighbors are all nice and will provide an insight of life in Lisbon. Rooms are comfortable, there's a kitchen, family room and dining room and the whole apartment is beautifully decorated. You can walk to the main sites from the apartment as well as to stores, supermarkets and restaurants.", created_at: "2016-01-05 17:24:00", updated_at: "2016-01-14 16:58:05", internet_speed: "Over 30mbps", short_term_rental: "Yes", level_of_noise: "Okay", walkability: "Great", link: "https://www.airbnb.com/rooms/3194716", city: "Lisbon", type: "Apartment", country_id: 180)

Place.create(name: "Seville, Spain", description: "Awesome apartment in a great location close to the main park in the city. The studio apartment has two bathrooms (one with a bathtub), a kitchen, a family room, dining room and two bedrooms. If you are a walker, you'll have no trouble reaching the center of the city through the park which is just next door, or following the river, but it can take half an hour to get to the center. Internet worked perfectly. There is a little bit of street noise, and since it is a converted space with no number on the door, it is hard to locate.", created_at: "2016-01-05 17:33:56", updated_at: "2016-01-14 17:00:56", internet_speed: "Over 30mbps", short_term_rental: "Yes", level_of_noise: "Okay", walkability: "Good", link: "https://www.airbnb.com/rooms/1768792", city: "Gibraltar", type: "Apartment", country_id: 86)

Place.create(name: "Gibraltar", description: "Charming apartment in Old Town, perfectly located. Gibraltar is very small so you can walk everywhere, but this apartment is very close to the Main Street. You have to go up several flights of stairs to reach it. The apartment is nicely decorated with a kitchen, bathroom, family and dining rooms. It can get very noisy with several constructions always going on around the neighborhood.", created_at: "2016-01-05 17:34:22", updated_at: "2016-01-14 17:05:00", image_url: "gibraltar1.png", internet_speed: "Over 30mps", short_term_rental: "Yes", level_of_noise: "Bad", walkability: "Great", food: "Accessible", ac_heater: "Heater")

Place.create(name: "Hakuna Matata Guest House", description: "Beautiful house with comfortable rooms with private bathrooms. The location is perfect to walk around town and it is inside a gated community. The house has a terrace from where you have an amazing view of three volcanoes. The owner, Eugenia, is incredibly nice.", created_at: "2016-03-30 18:32:46", updated_at: "2016-03-30 18:37:07", image_url: nil, internet_speed: "<10mbps", short_term_rental: "Yes", level_of_noise: "Quiet", walkability: "Great", food: nil, ac_heater: nil, link: "https://www.facebook.com/Hakuna-Matata-Guest-House...", city: "Antigua Guatemala", type: nil, country_id: 92)

Place.create(name: nil, description: "Great apartment very close to the city center. There is a metro station and supermarket just outside the building. It has two rooms and can fit up to 4 people. The hosts are super nice!", created_at: "2016-03-30 18:40:03", updated_at: "2016-03-30 18:40:03", image_url: nil, internet_speed: ">30mbps", short_term_rental: "Yes", level_of_noise: "Quiet", walkability: "Okay", food: nil, ac_heater: nil, link: "https://www.airbnb.com/rooms/5100076", city: "Prague", type: nil, country_id: 61)

Place.create(name: nil, description: "Beautiful traditional balinese bungalow in Ubud.", created_at: "2016-03-30 18:57:12", updated_at: "2016-03-30 18:57:12", image_url: nil, internet_speed: "<10mbps", short_term_rental: "Yes", level_of_noise: "Okay", walkability: "Okay", food: nil, ac_heater: nil, link: "https://www.airbnb.com/rooms/372543", city: "Ubud", type: nil, country_id: 105)

latin_america = Region.create(name: "Latin America", image_url:"latin-america.png")

north_america = Region.create(name: "North America", image_url:"north-america.png")

europe = Region.create(name: "Europe", image_url:"europe.png")

asia = Region.create(name: "Asia", image_url:"asia.png")

africa = Region.create(name: "Africa", image_url:"africa.png")

sea = Region.create(name: "South East Asia, Australia and New Zealand",  image_url:"../assets/oceania.png")


Country.create(name: "Afghanistan" , alpha2: "AF", region: asia, image_url: "af.svg")
Country.create(name: "Åland Islands" , alpha2: "AX", region: europe, image_url: "ax.svg")
Country.create(name: "Albania" , alpha2: "AL", region: europe, image_url: "al.svg")
Country.create(name: "Algeria" , alpha2: "DZ", region: africa, image_url: "dz.svg")
Country.create(name: "American Samoa" , alpha2: "AS", region: sea, image_url: "as.svg")
Country.create(name: "Andorra" , alpha2: "AD", region: europe, image_url: "ad.svg")
Country.create(name: "Angola" , alpha2: "AO", region: africa, image_url: "ao.svg")
Country.create(name: "Anguilla" , alpha2: "AI", region: north_america, image_url: "ai.svg")
Country.create(name: "Antarctica" , alpha2: "AQ", region: latin_america, image_url: "aq.svg")
Country.create(name: "Antigua and Barbuda" , alpha2: "AG", region: north_america, image_url: "ag.svg")
Country.create(name: "Argentina" , alpha2: "AR", region: latin_america, image_url: "ar.svg")
Country.create(name: "Armenia" , alpha2: "AM", region: asia, image_url: "am.svg")
Country.create(name: "Aruba" , alpha2: "AW", region: north_america, image_url: "aw.svg")
Country.create(name: "Australia" , alpha2: "AU", region: sea, image_url: "au.svg")
Country.create(name: "Austria" , alpha2: "AT", region: europe, image_url: "at.svg")
Country.create(name: "Azerbaijan" , alpha2: "AZ", region: asia, image_url: "az.svg")
Country.create(name: "Bahamas" , alpha2: "BS", region: north_america, image_url: "bs.svg")
Country.create(name: "Bahrain" , alpha2: "BH", region: asia, image_url: "bh.svg")
Country.create(name: "Bangladesh" , alpha2: "BD", region: asia, image_url: "bd.svg")
Country.create(name: "Barbados" , alpha2: "BB", region: north_america, image_url: "bb.svg")
Country.create(name: "Belarus" , alpha2: "BY", region: europe, image_url: "by.svg")
Country.create(name: "Belgium" , alpha2: "BE", region: europe, image_url: "be.svg")
Country.create(name: "Belize" , alpha2: "BZ", region: latin_america, image_url: "bz.svg")
Country.create(name: "Benin" , alpha2: "BJ", region: africa, image_url: "bj.svg")
Country.create(name: "Bermuda" , alpha2: "BM", region: north_america, image_url: "bm.svg")
Country.create(name: "Bhutan" , alpha2: "BT", region: asia, image_url: "bt.svg")
Country.create(name: "Bolivia" , alpha2: "BO", region: latin_america, image_url: "bo.svg")
Country.create(name: "Bonaire Sint Eustatius and Saba"  , alpha2: "BQ", region: latin_america, image_url: "bq.svg")	
Country.create(name: "Bosnia and Herzegovina" , alpha2: "BA", region: europe, image_url: "ba.svg")
Country.create(name: "Botswana" , alpha2: "BW", region: africa, image_url: "bw.svg")
Country.create(name: "Bouvet Island" , alpha2: "BV", region: latin_america, image_url: "bv.svg")
Country.create(name: "Brazil" , alpha2: "BR", region: latin_america, image_url: "br.svg")
Country.create(name: "British Indian Ocean Territory" , alpha2: "IO", region: asia, image_url: "io.svg")
Country.create(name: "Brunei Darussalam" , alpha2: "BN", region: sea, image_url: "bn.svg")
Country.create(name: "Bulgaria" , alpha2: "BG", region: europe, image_url: "bg.svg")
Country.create(name: "Burkina Faso" , alpha2: "BF", region: africa, image_url: "bf.svg")
Country.create(name: "Burundi" , alpha2: "BI", region: africa, image_url: "bi.svg")
Country.create(name: "Burma" , alpha2: "BU", region: sea, image_url: "bu.svg")
Country.create(name: "Cambodia" , alpha2: "KH", region: sea, image_url: "kh.svg")
Country.create(name: "Cameroon" , alpha2: "CM", region: africa, image_url: "cm.svg")
Country.create(name: "Canada" , alpha2: "CA", region: north_america, image_url: "ca.svg")
Country.create(name: "Cape Verde" , alpha2: "CV", region: africa, image_url: "cv.svg")
Country.create(name: "Cayman Islands" , alpha2: "KY", region: north_america, image_url: "ky.svg")
Country.create(name: "Central african Republic" , alpha2: "CF", region: africa, image_url: "cf.svg")
Country.create(name: "Chad" , alpha2: "TD", region: africa, image_url: "td.svg")
Country.create(name: "Chile" , alpha2: "CL", region: latin_america, image_url: "cl.svg")
Country.create(name: "China" , alpha2: "CN", region: asia, image_url: "cn.svg")
Country.create(name: "Christmas Island" , alpha2: "CX", region: sea, image_url: "cx.svg")
Country.create(name: "Cocos (Keeling) Islands" , alpha2: "CC", region: sea, image_url: "cc.svg")
Country.create(name: "Colombia" , alpha2: "CO", region: latin_america, image_url: "co.svg")
Country.create(name: "Comoros" , alpha2: "KM", region: africa, image_url: "km.svg")
Country.create(name: "Congo" , alpha2: "CG", region: africa, image_url: "cg.svg")
Country.create(name: "Congo, The Democratic Republic Of The" , alpha2: "CD", region: africa, image_url: "cd.svg")
Country.create(name: "Cook Islands" , alpha2: "CK", region: sea, image_url: "ck.svg")
Country.create(name: "Costa Rica" , alpha2: "CR", region: latin_america, image_url: "cr.svg")
Country.create(name: "Côte D'Ivoire" , alpha2: "CI", region: africa, image_url: "ci.svg")
Country.create(name: "Croatia" , alpha2: "HR", region: europe, image_url: "hr.svg")
Country.create(name: "Cuba" , alpha2: "CU", region: latin_america, image_url: "cu.svg")
Country.create(name: "Curaçao" , alpha2: "CW", region: latin_america, image_url: "cw.svg")
Country.create(name: "Cyprus" , alpha2: "CY", region: europe, image_url: "cy.svg")
Country.create(name: "Czech Republic" , alpha2: "CZ", region: europe, image_url: "cz.svg")
Country.create(name: "Denmark" , alpha2: "DK", region: europe, image_url: "dk.svg")
Country.create(name: "Djibouti" , alpha2: "DJ", region: africa, image_url: "dj.svg")
Country.create(name: "Dominica" , alpha2: "DM", region: north_america, image_url: "dm.svg")
Country.create(name: "Dominican Republic" , alpha2: "DO", region: latin_america, image_url: "do.svg")
Country.create(name: "Ecuador" , alpha2: "EC", region: latin_america, image_url: "ec.svg")
Country.create(name: "Egypt" , alpha2: "EG", region: africa, image_url: "eg.svg")
Country.create(name: "El Salvador" , alpha2: "SD", region: latin_america, image_url: "sd.svg")
Country.create(name: "Equatorial Guinea" , alpha2: "GQ", region: africa, image_url: "gq.svg")
Country.create(name: "Eritrea" , alpha2: "ER", region: africa, image_url: "er.svg")
Country.create(name: "Estonia" , alpha2: "EE", region: europe, image_url: "ee.svg")
Country.create(name: "Ethiopia" , alpha2: "ET", region: africa, image_url: "et.svg")
Country.create(name: "Falkland Islands (Malvinas)" , alpha2: "FK", region: latin_america, image_url: "fk.svg")
Country.create(name: "Faroe Islands" , alpha2: "FO", region: europe, image_url: "fo.svg")
Country.create(name: "Fiji" , alpha2: "FJ", region: sea, image_url: "fj.svg")
Country.create(name: "Finland" , alpha2: "FI", region: europe, image_url: "fi.svg")
Country.create(name: "France" , alpha2: "FR", region: europe, image_url: "fr.svg")
Country.create(name: "French Guiana" , alpha2: "GF", region: latin_america, image_url: "gf.svg")
Country.create(name: "French Polynesia" , alpha2: "PF", region: sea, image_url: "pf.svg")
Country.create(name: "French Southern Territories" , alpha2: "TF", region: latin_america, image_url: "tf.svg")
Country.create(name: "Gabon" , alpha2: "GA", region: africa, image_url: "ga.svg")
Country.create(name: "Gambia" , alpha2: "GM", region: africa, image_url: "gm.svg")
Country.create(name: "Georgia" , alpha2: "GE", region: asia, image_url: "ge.svg")
Country.create(name: "Germany" , alpha2: "DE", region: europe, image_url: "de.svg")
Country.create(name: "Ghana" , alpha2: "GH", region: africa, image_url: "gh.svg")
Country.create(name: "Gibraltar" , alpha2: "GI", region: europe, image_url: "gi.svg")
Country.create(name: "Greece" , alpha2: "GR", region: europe, image_url: "gr.svg")
Country.create(name: "Greenland" , alpha2: "GL", region: europe, image_url: "gl.svg")
Country.create(name: "Grenada" , alpha2: "GD", region: north_america, image_url: "gd.svg")
Country.create(name: "Guadeloupe" , alpha2: "GP", region: north_america, image_url: "gp.svg")
Country.create(name: "Guam" , alpha2: "GU", region: sea, image_url: "gu.svg")
Country.create(name: "Guatemala" , alpha2: "GT", region: latin_america, image_url: "gt.svg")
Country.create(name: "Guernsey" , alpha2: "GG", region: europe, image_url: "gg.svg")
Country.create(name: "Guinea" , alpha2: "GN", region: africa, image_url: "gn.svg")
Country.create(name: "Guinea-Bissau" , alpha2: "GW", region: africa, image_url: "gw.svg")
Country.create(name: "Guyana" , alpha2: "GY", region: latin_america, image_url: "gy.svg")
Country.create(name: "Haiti" , alpha2: "HT", region: north_america, image_url: "ht.svg")
Country.create(name: "Heard and McDonald Islands" , alpha2: "HM", region: sea, image_url: "hm.svg")
Country.create(name: "Holy See (Vatican City State)" , alpha2: "VA", region: europe, image_url: "va.svg")
Country.create(name: "Honduras" , alpha2: "HN", region: latin_america, image_url: "hn.svg")
Country.create(name: "Hong Kong" , alpha2: "HK", region: asia, image_url: "hk.svg")
Country.create(name: "Hungary" , alpha2: "HU", region: europe, image_url: "hu.svg")
Country.create(name: "Iceland" , alpha2: "IS", region: europe, image_url: "is.svg")
Country.create(name: "India" , alpha2: "IN", region: asia, image_url: "in.svg")
Country.create(name: "Indonesia" , alpha2: "ID", region: sea, image_url: "id.svg")
Country.create(name: "Iran, Islamic Republic Of" , alpha2: "IR", region: asia, image_url: "ir.svg")
Country.create(name: "Iraq" , alpha2: "IQ", region: asia, image_url: "iq.svg")
Country.create(name: "Ireland" , alpha2: "IE", region: europe, image_url: "ie.svg")
Country.create(name: "Isle of Man" , alpha2: "IM", region: europe, image_url: "im.svg")
Country.create(name: "Israel" , alpha2: "IL", region: asia, image_url: "il.svg")
Country.create(name: "Italy" , alpha2: "IT", region: europe, image_url: "it.svg")
Country.create(name: "Jamaica" , alpha2: "JM", region: north_america, image_url: "jm.svg")
Country.create(name: "Japan" , alpha2: "JP", region: asia, image_url: "jp.svg")
Country.create(name: "Jersey" , alpha2: "JE", region: europe, image_url: "je.svg")
Country.create(name: "Jordan" , alpha2: "JO", region: asia, image_url: "jo.svg")
Country.create(name: "Kazakhstan" , alpha2: "KZ", region: asia, image_url: "kz.svg")
Country.create(name: "Kenya" , alpha2: "KE", region: africa, image_url: "ke.svg")
Country.create(name: "Kiribati" , alpha2: "KI", region: sea, image_url: "ki.svg")
Country.create(name: "Korea, Democratic People's Republic Of" , alpha2: "KP", region: asia, image_url: "kp.svg")
Country.create(name: "Korea, Republic of" , alpha2: "KR", region: asia, image_url: "kr.svg")
Country.create(name: "Kuwait" , alpha2: "KW", region: asia, image_url: "kw.svg")
Country.create(name: "Kyrgyzstan" , alpha2: "KG", region: asia, image_url: "kg.svg")
Country.create(name: "Lao People's Democratic Republic" , alpha2: "LA", region: sea, image_url: "la.svg")
Country.create(name: "Latvia" , alpha2: "LV", region: europe, image_url: "lv.svg")
Country.create(name: "Lebanon" , alpha2: "LB", region: asia, image_url: "lb.svg")
Country.create(name: "Lesotho" , alpha2: "LS", region: africa, image_url: "ls.svg")
Country.create(name: "Liberia" , alpha2: "LR", region: africa, image_url: "lr.svg")
Country.create(name: "Libya" , alpha2: "LY", region: africa, image_url: "ly.svg")
Country.create(name: "Liechtenstein" , alpha2: "LI", region: europe, image_url: "li.svg")
Country.create(name: "Lithuania" , alpha2: "LT", region: europe, image_url: "lt.svg")
Country.create(name: "Luxembourg" , alpha2: "LU", region: europe, image_url: "lu.svg")
Country.create(name: "Macao" , alpha2: "MO", region: asia, image_url: "mo.svg")
Country.create(name: "Macedonia, the Former Yugoslav Republic Of" , alpha2: "MK", region: europe, image_url: "mk.svg")
Country.create(name: "Madagascar" , alpha2: "MG", region: africa, image_url: "mg.svg")
Country.create(name: "Malawi" , alpha2: "MW", region: africa, image_url: "mw.svg")
Country.create(name: "Malaysia" , alpha2: "MY", region: sea, image_url: "my.svg")
Country.create(name: "Maldives" , alpha2: "MV", region: asia, image_url: "mv.svg")
Country.create(name: "Mali" , alpha2: "ML", region: africa, image_url: "ml.svg")
Country.create(name: "Malta" , alpha2: "MT", region: europe, image_url: "mt.svg")
Country.create(name: "Marshall Islands" , alpha2: "MH", region: sea, image_url: "mh.svg")
Country.create(name: "Martinique" , alpha2: "MQ", region: north_america, image_url: "mq.svg")
Country.create(name: "Mauritania" , alpha2: "MR", region: africa, image_url: "mr.svg")
Country.create(name: "Mauritius" , alpha2: "MU", region: africa, image_url: "mu.svg")
Country.create(name: "Mayotte" , alpha2: "YT", region: africa, image_url: "yt.svg")
Country.create(name: "Mexico" , alpha2: "MX", region: latin_america, image_url: "mx.svg")
Country.create(name: "Micronesia, Federated States Of" , alpha2: "FM", region: sea, image_url: "fm.svg")
Country.create(name: "Moldova, Republic of" , alpha2: "MD", region: europe, image_url: "md.svg")
Country.create(name: "Monaco" , alpha2: "MC", region: europe, image_url: "mc.svg")
Country.create(name: "Mongolia" , alpha2: "MN", region: asia, image_url: "mn.svg")
Country.create(name: "Montenegro" , alpha2: "ME", region: europe, image_url: "me.svg")
Country.create(name: "Montserrat" , alpha2: "MS", region: north_america, image_url: "ms.svg")
Country.create(name: "Morocco" , alpha2: "MA", region: africa, image_url: "ma.svg")
Country.create(name: "Mozambique" , alpha2: "MZ", region: africa, image_url: "mz.svg")
Country.create(name: "Myanmar" , alpha2: "MM", region: sea, image_url: "mm.svg")
Country.create(name: "Namibia" , alpha2: "NA", region: africa, image_url: "na.svg")
Country.create(name: "Nauru" , alpha2: "NR", region: sea, image_url: "nr.svg")
Country.create(name: "Nepal" , alpha2: "NP", region: asia, image_url: "np.svg")
Country.create(name: "Netherlands" , alpha2: "NL", region: europe, image_url: "nl.svg")
Country.create(name: "Netherlands Antilles" , alpha2: "AQ", region: north_america, image_url: "aq.svg")
Country.create(name: "New Caledonia" , alpha2: "NC", region: sea, image_url: "nc.svg")
Country.create(name: "New Zealand" , alpha2: "NZ", region: sea, image_url: "nz.svg")
Country.create(name: "Nicaragua" , alpha2: "NI", region: latin_america, image_url: "ni.svg")
Country.create(name: "Niger" , alpha2: "NE", region: africa, image_url: "ne.svg")
Country.create(name: "Nigeria" , alpha2: "NG", region: africa, image_url: "ng.svg")
Country.create(name: "Niue" , alpha2: "NU", region: sea, image_url: "nu.svg")
Country.create(name: "Norfolk Island" , alpha2: "NF", region: sea, image_url: "nf.svg")
Country.create(name: "Northern Mariana Islands" , alpha2: "MP", region: sea, image_url: "mp.svg")
Country.create(name: "Norway" , alpha2: "NO", region: europe, image_url: "no.svg")
Country.create(name: "Oman" , alpha2: "OM", region: asia, image_url: "om.svg")
Country.create(name: "Pakistan" , alpha2: "PK", region: asia, image_url: "pk.svg")
Country.create(name: "Palau" , alpha2: "PW", region: sea, image_url: "pw.svg")
Country.create(name: "Palestine, State of" , alpha2: "PS", region: asia, image_url: "ps.svg")
Country.create(name: "Panama" , alpha2: "PA", region: latin_america, image_url: "pa.svg")
Country.create(name: "Papua New Guinea" , alpha2: "PG", region: sea, image_url: "pg.svg")
Country.create(name: "Paraguay" , alpha2: "PY", region: latin_america, image_url: "py.svg")
Country.create(name: "Peru" , alpha2: "PE", region: latin_america, image_url: "pe.svg")
Country.create(name: "Philippines" , alpha2: "PH", region: sea, image_url: "ph.svg")
Country.create(name: "Pitcairn" , alpha2: "PN", region: sea, image_url: "pn.svg")
Country.create(name: "Poland" , alpha2: "PL", region: europe, image_url: "pl.svg")
Country.create(name: "Portugal" , alpha2: "PT", region: europe, image_url: "pt.svg")
Country.create(name: "Puerto Rico" , alpha2: "PR", region: latin_america, image_url: "pr.svg")
Country.create(name: "Qatar" , alpha2: "QA", region: asia, image_url: "qa.svg")
Country.create(name: "Réunion" , alpha2: "RE", region: africa, image_url: "re.svg")
Country.create(name: "Romania" , alpha2: "RO", region: europe, image_url: "ro.svg")
Country.create(name: "Russian Federation" , alpha2: "RU", region: europe, image_url: "ru.svg")
Country.create(name: "Rwanda" , alpha2: "RW", region: africa, image_url: "rw.svg")
Country.create(name: "Saint Barthélemy" , alpha2: "BL", region: north_america, image_url: "bl.svg")
Country.create(name: "Saint Helena" , alpha2: "SH", region: africa, image_url: "sh.svg")
Country.create(name: "Saint Kitts And Nevis" , alpha2: "KN", region: north_america, image_url: "kn.svg")
Country.create(name: "Saint Lucia" , alpha2: "LC", region: north_america, image_url: "lc.svg")
Country.create(name: "Saint Martin" , alpha2: "MF", region: north_america, image_url: "mf.svg")
Country.create(name: "Saint Pierre And Miquelon" , alpha2: "PM", region: north_america, image_url: "pm.svg")
Country.create(name: "Saint Vincent And The Grenadines" , alpha2: "VC", region: north_america, image_url: "vc.svg")
Country.create(name: "Samoa" , alpha2: "WS", region: sea, image_url: "ws.svg")
Country.create(name: "San Marino" , alpha2: "SM", region: europe, image_url: "sm.svg")
Country.create(name: "Sao Tome and Principe" , alpha2: "ST", region: africa, image_url: "st.svg")
Country.create(name: "Saudi Arabia" , alpha2: "SA", region: asia, image_url: "sa.svg")
Country.create(name: "Senegal" , alpha2: "SN", region: africa, image_url: "sn.svg")
Country.create(name: "Serbia" , alpha2: "RS", region: europe, image_url: "rs.svg")
Country.create(name: "Seychelles" , alpha2: "SC", region: africa, image_url: "sc.svg")
Country.create(name: "Sierra Leone" , alpha2: "SL", region: europe, image_url: "sl.svg")
Country.create(name: "Singapore" , alpha2: "SG", region: sea, image_url: "sg.svg")
Country.create(name: "Sint Maarten" , alpha2: "SX", region: north_america, image_url: "sx.svg")
Country.create(name: "Slovakia" , alpha2: "SK", region: europe, image_url: "sk.svg")
Country.create(name: "Slovenia" , alpha2: "SI", region: europe, image_url: "si.svg")
Country.create(name: "Solomon Islands" , alpha2: "SB", region: sea, image_url: "sb.svg")
Country.create(name: "Somalia" , alpha2: "SO", region: africa, image_url: "so.svg")
Country.create(name: "South Africa" , alpha2: "ZA", region: africa, image_url: "za.svg")
Country.create(name: "South Georgia and the South Sandwich Islands" , alpha2: "GS", region: latin_america, image_url: "gs.svg")
Country.create(name: "South Sudan" , alpha2: "SS", region: africa, image_url: "ss.svg")
Country.create(name: "Spain" , alpha2: "ES", region: europe, image_url: "es.svg")
Country.create(name: "Sri Lanka" , alpha2: "LK", region: asia, image_url: "lk.svg")
Country.create(name: "Sudan" , alpha2: "SD", region: africa, image_url: "sd.svg")
Country.create(name: "Suriname" , alpha2: "SR", region: latin_america, image_url: "sr.svg")
Country.create(name: "Svalbard And Jan Mayen" , alpha2: "SJ", region: europe, image_url: "sj.svg")
Country.create(name: "Swaziland" , alpha2: "SZ", region: africa, image_url: "sz.svg")
Country.create(name: "Sweden" , alpha2: "SE", region: europe, image_url: "se.svg")
Country.create(name: "Switzerland" , alpha2: "CH", region: europe, image_url: "ch.svg")
Country.create(name: "Syrian Arab Republic" , alpha2: "SY", region: asia, image_url: "sy.svg")
Country.create(name: "Taiwan, Republic Of China" , alpha2: "TW", region: asia, image_url: "tw.svg")
Country.create(name: "Tajikistan" , alpha2: "TJ", region: asia, image_url: "tj.svg")
Country.create(name: "Tanzania, United Republic of" , alpha2: "TZ", region: africa, image_url: "tz.svg")
Country.create(name: "Thailand" , alpha2: "TH", region: sea, image_url: "th.svg")
Country.create(name: "Timor-Leste" , alpha2: "TL", region: sea, image_url: "tl.svg")
Country.create(name: "Togo" , alpha2: "TG", region: africa, image_url: "tg.svg")
Country.create(name: "Tokelau" , alpha2: "TK", region: sea, image_url: "tk.svg")
Country.create(name: "Tonga" , alpha2: "TO", region: sea, image_url: "to.svg")
Country.create(name: "Trinidad and Tobago" , alpha2: "TT", region: latin_america, image_url: "tt.svg")
Country.create(name: "Tunisia" , alpha2: "TN", region: africa, image_url: "tn.svg")
Country.create(name: "Turkey" , alpha2: "TR", region: asia, image_url: "tr.svg")
Country.create(name: "Turkmenistan" , alpha2: "TM", region: asia, image_url: "tm.svg")
Country.create(name: "Turks and Caicos Islands" , alpha2: "TC", region: north_america, image_url: "tc.svg")
Country.create(name: "Tuvalu" , alpha2: "TV", region: sea, image_url: "tv.svg")
Country.create(name: "Uganda" , alpha2: "UG", region: africa, image_url: "ug.svg")
Country.create(name: "Ukraine" , alpha2: "UA", region: europe, image_url: "ua.svg")
Country.create(name: "United Arab Emirates" , alpha2: "AE", region: asia, image_url: "ae.svg")
Country.create(name: "United Kingdom" , alpha2: "GB", region: europe, image_url: "gb.svg")
Country.create(name: "United States" , alpha2: "US", region: north_america, image_url: "us.svg")
Country.create(name: "United States Minor Outlying Islands" , alpha2: "UM", region: north_america, image_url: "um.svg")
Country.create(name: "Uruguay" , alpha2: "UY", region: latin_america, image_url: "uy.svg")
Country.create(name: "Uzbekistan" , alpha2: "UZ", region: asia, image_url: "uz.svg")
Country.create(name: "Vanuatu" , alpha2: "VU", region: sea, image_url: "vu.svg")
Country.create(name: "Venezuela Bolivarian Republic of" , alpha2: "VE", region: latin_america, image_url: "ve.svg")
Country.create(name: "Vietnam" , alpha2: "VN", region: sea, image_url: "vn.svg")
Country.create(name: "Virgin Islands British" , alpha2: "VG", region: north_america, image_url: "vg.svg")
Country.create(name: "Virgin Islands U.S." , alpha2: "VI", region: north_america, image_url: "vi.svg")
Country.create(name: "Wallis and Futuna" , alpha2: "WF", region: sea, image_url: "wf.svg")
Country.create(name: "Western Sahara" , alpha2: "EH", region: africa, image_url: "eh.svg")
Country.create(name: "Yemen" , alpha2: "YE", region: asia, image_url: "ye.svg")
Country.create(name: "Zambia" , alpha2: "ZM", region: africa, image_url: "zm.svg")
Country.create(name: "Zimbabwe" , alpha2: "ZW", region: africa, image_url: "zw.svg")